CATALOG = [
    {
        "id": "instant-noodles",
        "name": "Instant Noodles",
        "description": "Quick merienda staple for an online grocery shelf.",
        "category": "refreshments",
        "price": 18.0,
        "pricing_unit": "piece",
        "stock_quantity": 24,
    },
    {
        "id": "3in1-coffee",
        "name": "3-in-1 Coffee Pack",
        "description": "Convenient single-serve coffee sachets for daily use.",
        "category": "housekeeping",
        "price": 12.0,
        "pricing_unit": "piece",
        "stock_quantity": 30,
    },
    {
        "id": "canned-sardines",
        "name": "Canned Sardines",
        "description": "Affordable pantry essential commonly stocked in online grocery stores.",
        "category": "wellness",
        "price": 28.0,
        "pricing_unit": "piece",
        "stock_quantity": 18,
    },
    {
        "id": "bottled-water",
        "name": "Bottled Water",
        "description": "Everyday drinking water for quick neighborhood purchases.",
        "category": "refreshments",
        "price": 15.0,
        "pricing_unit": "piece",
        "stock_quantity": 36,
    },
]
